services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite_data:/data
    ports:
      - "3001:3001"
    environment:
      - DATABASE_PATH=/data/database.sqlite
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  sqlite_data:
